Repository cert-manager/csi-driver-spiffe, pull requests merged in 2022-05, with the labels that each got.

#4 Bump csi lib v0.2.2
  Makefile
  go.mod
  go.sum
  hack/tools/tools.go
  internal/approver/app/app.go
  internal/approver/app/options/options.go
  internal/approver/controller/controller.go
  internal/approver/controller/controller_test.go
  internal/approver/controller/test/suite.go
  internal/approver/evaluator/evaluator.go
  internal/approver/evaluator/evaluator_test.go
  internal/approver/evaluator/extensions_test.go
  internal/approver/evaluator/fake/fake.go
  internal/csi/app/options/options.go
  internal/csi/driver/driver.go
  test/e2e/framework/config/config.go
  test/e2e/framework/framework.go
  test/e2e/suite/approval/approval.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#5 Update links to cert-manager/cert-manager in SECURITY.md and README.md
  README.md
  SECURITY.md
Labels: dco-signoff: yes, size/XS, lgtm, approved

#6 Updates to go v1.18 in Dockerfiles
  Dockerfile.approver
  Dockerfile.driver
Labels: dco-signoff: yes, size/XS, lgtm, approved

#7 Bumps bump-csi-node-driver-registrar to `v2.5.0`
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#8 Adds liveness probe to csi-driver
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#13 Make CSI driver spiffe writeFiles compatable with go-spiffe `x509svid.Parse`
  go.mod
  go.sum
  internal/csi/driver/camanager.go
  internal/csi/driver/camanager_test.go
  internal/csi/driver/driver.go
  internal/csi/driver/driver_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#9 Configurable side cars
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
  deploy/charts/csi-driver-spiffe/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#11 Adds verify-helm-docs.sh and update-helm-docs.sh scripts. Verify helm-docs during lint
  Makefile
  deploy/charts/csi-driver-spiffe/README.md
  go.mod
  go.sum
  hack/tools/tools.go
  hack/update-helm-docs.sh
  hack/verify-helm-docs.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#10 Updates app version to v0.2.0
  Makefile
  deploy/charts/csi-driver-spiffe/Chart.yaml
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/values.yaml
  internal/csi/driver/driver.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#14 Update logo to smaller version, fix broken HTML
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved
