Repository cert-manager/csi-driver-spiffe, pull requests merged in 2023-04, with the labels that each got.

#24 Add missing --csi-driver-name option to daemonset
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, ok-to-test

#34 Bump helm docs
  Makefile
  go.mod
  go.sum
  hack/verify-helm-docs.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#36 Bump to v0.4.0 for release
  Makefile
  deploy/charts/csi-driver-spiffe/Chart.yaml
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S
