Repository cert-manager/csi-driver-spiffe, pull requests merged in 2023-02, with the labels that each got.

#21 Updates dependencies
  go.mod
  go.sum
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#26 Bump helm version, improve install, add chart target
  Makefile
Labels: dco-signoff: yes, lgtm, approved, size/S

#27 Ensures that CSI driver sidecar images are latest from registry.k8s.io
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#29 Bump go, deps, base images
  Dockerfile.approver
  Dockerfile.driver
  Makefile
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, size/M

#28 Change to use p256 instead of p521
  internal/approver/evaluator/evaluator.go
  internal/approver/evaluator/evaluator_test.go
  internal/csi/driver/driver_test.go
  internal/csi/driver/util.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#30 Bump versions, fix old info
  Makefile
  deploy/charts/csi-driver-spiffe/Chart.yaml
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/templates/NOTES.txt
  deploy/charts/csi-driver-spiffe/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#31 Change release version to use a v, fixes generation of chart
  Makefile
Labels: dco-signoff: yes, lgtm, approved, size/S

#22 Use `/usr/bin/env` instead of `/bin/bash` in hack scripts
  hack/update-helm-docs.sh
  hack/verify-boilerplate.sh
  hack/verify-helm-docs.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved
