Repository cert-manager/csi-driver-spiffe, pull requests merged in 2024-02, with the labels that each got.

#86 Use helm-tool to generate Helm README.md
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/values.yaml
  make/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/XL

#87 Fix release target and add approver image
  .github/workflows/release.yaml
  make/02_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#88 Fix broken link in Chart.yaml for csi-driver
  deploy/charts/csi-driver-spiffe/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#80 Enable helm-tool linter and schema generator
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/templates/_helpers.tpl
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
  deploy/charts/csi-driver-spiffe/templates/deployment.yaml
  deploy/charts/csi-driver-spiffe/values.linter.exceptions
  deploy/charts/csi-driver-spiffe/values.schema.json
  deploy/charts/csi-driver-spiffe/values.yaml
  make/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/XL

#95 use exit code from recommended range
  internal/approver/controller/controller.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#97 Use same include statement for labels everywhere & add labels to pod templates
  deploy/charts/csi-driver-spiffe/templates/clusterrole.yaml
  deploy/charts/csi-driver-spiffe/templates/clusterrolebinding.yaml
  deploy/charts/csi-driver-spiffe/templates/csidriver.yaml
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
  deploy/charts/csi-driver-spiffe/templates/deployment.yaml
  deploy/charts/csi-driver-spiffe/templates/metrics-service.yaml
  deploy/charts/csi-driver-spiffe/templates/metrics-servicemonitor.yaml
  deploy/charts/csi-driver-spiffe/templates/role.yaml
  deploy/charts/csi-driver-spiffe/templates/rolebinding.yaml
  deploy/charts/csi-driver-spiffe/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#94 Add design for runtime configuration of issuers
  design/2024-02-21-install-without-issuer.md
Labels: dco-signoff: yes, lgtm, approved, size/L

#98 Helm Add commonLabels option
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/templates/_helpers.tpl
  deploy/charts/csi-driver-spiffe/values.schema.json
  deploy/charts/csi-driver-spiffe/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S
