Repository cert-manager/csi-driver-spiffe, pull requests merged in 2024-01, with the labels that each got.

#60 Add certificate requests annotations flag
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
  deploy/charts/csi-driver-spiffe/values.yaml
  internal/approver/controller/controller.go
  internal/csi/app/app.go
  internal/csi/app/options/options.go
  internal/csi/driver/driver.go
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test

#61 Migrate to ginkgo v2
  Makefile
  go.mod
  go.sum
  hack/tools/tools.go
  internal/approver/controller/test/controller.go
  internal/approver/controller/test/controller_test.go
  internal/approver/controller/test/suite.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/framework.go
  test/e2e/suite/approval/approval.go
  test/e2e/suite/carotation/carotation.go
  test/e2e/suite/fsgroup/fsgroup.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#66 Upgrade repository-base module
  .github/workflows/make-self-upgrade.yaml
  Makefile
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/Makefile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#73 Use fixed version for busybox image
  make/00_mod.mk
  test/e2e/suite/carotation/carotation.go
  test/e2e/suite/fsgroup/fsgroup.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#74 Upgrade oci-image module
  klone.yaml
  make/00_mod.mk
  make/_shared/oci-image/01_mod.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#79 Use standardised release process
  make/02_mod.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved

#75 Add version info to binary at compile time
  internal/csi/app/app.go
  internal/csi/driver/camanager.go
  internal/csi/driver/driver.go
  internal/version/version.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#82 Update Chart.yaml properties
  deploy/charts/csi-driver-spiffe/Chart.yaml
  deploy/charts/csi-driver-spiffe/README.md
Labels: dco-signoff: yes, lgtm, approved, size/M
