Repository cert-manager/csi-driver-spiffe, pull requests merged in 2024-04, with the labels that each got.

#116 Upgrade repository-base module
  .github/dependabot.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base-dependabot/.github/dependabot.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#123 Two minor tweaks
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
  internal/approver/evaluator/evaluator.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#124 Rename DaemonSet for easier tab completion
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#122 Fix gosec issues and enable gosec linter
  .golangci.yaml
  internal/csi/rootca/file_test.go
  test/e2e/suite/carotation/carotation.go
  test/e2e/suite/fsgroup/fsgroup.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#126 Increase timeouts for camanager test
  internal/csi/driver/camanager_test.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#130 Move parsing of custom annotations to testable function
  internal/annotations/annotations.go
  internal/csi/app/app.go
  internal/csi/driver/driver.go
  internal/csi/driver/driver_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#125 Remove issuerRef from approver
  deploy/charts/csi-driver-spiffe/templates/deployment.yaml
  internal/approver/app/app.go
  internal/approver/app/options/options.go
  internal/approver/controller/controller.go
  internal/approver/controller/test/suite.go
  test/e2e/suite/approval/approval.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#135 Add env var for focusing on individual e2e tests
  make/test-e2e.mk
Labels: dco-signoff: yes, size/XS, lgtm, approved
