Repository cert-manager/csi-driver-spiffe, pull requests merged in 2024-05, with the labels that each got.

#136 Add e2e util package to abstract common e2e tasks
  test/e2e/suite/carotation/carotation.go
  test/e2e/suite/fsgroup/fsgroup.go
  test/e2e/util/util.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#144 Change approval of e2e issuer to use cmctl
  make/test-e2e.mk
Labels: dco-signoff: yes, lgtm, approved, size/S

#50 Added tolerations,nodeSelector,affinity,topologySpreadConstraints
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
  deploy/charts/csi-driver-spiffe/templates/deployment.yaml
  deploy/charts/csi-driver-spiffe/values.schema.json
  deploy/charts/csi-driver-spiffe/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/L, ok-to-test

#141 Allow runtime configuration of issuers
  deploy/charts/csi-driver-spiffe/README.md
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
  deploy/charts/csi-driver-spiffe/templates/role.yaml
  deploy/charts/csi-driver-spiffe/templates/rolebinding.yaml
  deploy/charts/csi-driver-spiffe/values.schema.json
  deploy/charts/csi-driver-spiffe/values.yaml
  internal/csi/app/app.go
  internal/csi/app/options/options.go
  internal/csi/driver/driver.go
  make/test-e2e.mk
  test/e2e/framework/config/config.go
  test/e2e/suite/import.go
  test/e2e/suite/runtimeconfiguration/runtimeconfiguration.go
  test/e2e/util/util.go
Labels: dco-signoff: yes, lgtm, approved, size/XL
