Repository cert-manager/csi-driver-spiffe, pull requests merged in 2025-04, with the labels that each got.

#270 Only watch for runtime configuration if provided
  internal/csi/driver/driver.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#280 Bump x/net to fix CVE-2025-22872 reported by trivy
  RELEASE.md
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, size/M

#281 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/oci-build/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#282 Add dependency licenses to repo and OCI image
  LICENSES
  klone.yaml
  make/_shared/licenses/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/L

#284 Fix bad security context on DaemonSet
  deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved
